const ACTIONS_TYPES = Object.freeze({
  GET_ERROR: "GET_ERROR",
  
  // CATEGORY
  CATEGORY_GET_LIST: "CATEGORY_GET_LIST",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  // BRAND
  BRAND_GET_LIST: "BRAND_GET_LIST",
  BRAND_CREATE: "BRAND_CREATE",
})
export default ACTIONS_TYPES